### ISSUE TITLE
Admin port gives 404 error

### ISSUE THREAD

**Issue by lgwapnitsky** [prismelabs/analytics#2]
from my docker file:

```
    ports:
      - 8090:8000
      - 9090:9090

    environment:
      # Configuration options are listed and explained here:
      # https://www.prismeanalytics.com/docs/set-up/configuration/configure-server/default-mode
      #
      PRISME_ACCESS_LOG: '/dev/stdout'
      PRISME_DEBUG: 'false'
      PRISME_PORT: '8090'
      PRISME_TRUST_PROXY: 'true'
      PRISME_CLICKHOUSE_TLS: 'false'
      PRISME_CLICKHOUSE_HOSTPORT: 'clickhouse.localhost:9000'
      PRISME_CLICKHOUSE_USER: 'default'
      PRISME_CLICKHOUSE_PASSWORD: 'password'
      PRISME_CLICKHOUSE_DB: 'prisme'
      PRISME_SOURCE_REGISTRY_SOURCES: 'localhost,mywebsite.localhost,foo.mywebsite.localhost'
      PRISME_GRAFANA_URL: 'http://grafana.localhost:3000'
      PRISME_GRAFANA_USER: 'admin'
      PRISME_GRAFANA_PASSWORD: 'admin'
      PRISME_ADMIN_HOSTPORT: '0.0.0.0:9090'
```

Going to port 9090 gives me a 404 error
